version: '3.9'

services:
  db:
    image: postgres:16
    container_name: callbus_db
    env_file:
      - ../../.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-callbus}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-callbus_pw}
      POSTGRES_DB: ${POSTGRES_DB:-callbus_db}
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ../../
      dockerfile: apps/backend/Dockerfile
    container_name: callbus_backend
    env_file:
      - ../../.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '${BACKEND_PORT:-8000}:8000'
    volumes:
      - ../../apps/backend/app:/app/app
    command: ['bash', '-lc', 'uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload']

volumes:
  db_data:
